// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEDqSnU3ufDFVlquDx7IlN0NbTaAPWH0c',
    appId: '1:794992697927:web:3b1f707ac7da2e0ab68762',
    messagingSenderId: '794992697927',
    projectId: 'ecommerce-5ec87',
    authDomain: 'ecommerce-5ec87.firebaseapp.com',
    storageBucket: 'ecommerce-5ec87.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwsvyDJKXoC52lgnT92JqRMbhtX9tSEmI',
    appId: '1:794992697927:android:dc3d6b6d037073dfb68762',
    messagingSenderId: '794992697927',
    projectId: 'ecommerce-5ec87',
    storageBucket: 'ecommerce-5ec87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCReEJpfoVk1URu5okssworfjs3Ahos6u0',
    appId: '1:794992697927:ios:07d00a6212b5f7fcb68762',
    messagingSenderId: '794992697927',
    projectId: 'ecommerce-5ec87',
    storageBucket: 'ecommerce-5ec87.appspot.com',
    androidClientId: '794992697927-9a2ampst0g4e61t2qll7u0qbbshgpgrb.apps.googleusercontent.com',
    iosClientId: '794992697927-ijj8n2sc9hk3i89o5faervep1hug8orq.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );
}
